boostcampwm-2024/web35-watchducks

backend/proxy-server/.eslintignore
backend/proxy-server/eslint.config.js
backend/proxy-server/src/common/interface/log.interface.ts
backend/proxy-server/src/common/logger/fastify.logger.ts
backend/proxy-server/src/common/logger/logger.interface.ts
backend/proxy-server/src/error/core/proxy-error.handler.ts
backend/proxy-server/src/proxy/config/fastify.config.ts
backend/proxy-server/src/proxy/proxy-server-fastify.ts
backend/proxy-server/test/common/fastify.logger.test.ts
backend/proxy-server/test/proxy/proxy-server-fastify.test.ts
backend/proxy-server/test/proxy/proxy-service.test.ts

#23 
- 아직 코드 리팩토링이 필요한 부분이 조금 더 있을 것 같습니다.

[BE] 로그 수집 시스템 구현

---

front/netlify.toml

[FE] netlify설정파일 추가

---

backend/console-server/src/app.controller.ts
backend/console-server/src/config/mailer.config.ts
backend/console-server/src/log/log.module.ts
backend/console-server/src/mail/mail.module.ts
backend/console-server/src/mail/mail.service.spec.ts
backend/console-server/src/mail/mail.service.ts
backend/console-server/src/project/dto/create-project-response.dto.ts
backend/console-server/src/project/dto/create-project.dto.ts
backend/console-server/src/project/project.controller.spec.ts
backend/console-server/src/project/project.controller.ts
backend/console-server/src/project/project.module.ts
backend/console-server/src/project/project.service.spec.ts
backend/console-server/src/project/project.service.ts

[BE] 탭 사이즈 조정 (style)

---

backend/proxy-server/package-lock.json
backend/proxy-server/package.json
backend/proxy-server/test/common/logger/fastify.logger.test.ts
backend/proxy-server/test/domain/log/http-log-entity.test.ts
backend/proxy-server/test/domain/log/log.repository.test.ts
backend/proxy-server/test/domain/log/log.service.test.ts
backend/proxy-server/test/integration.test.ts
backend/proxy-server/test/server/utils.test.ts

#57 
- Proxy Server 통합 테스트
✓ 요청을 로깅할 수 있어야 한다. (235 ms)
✓ 예상한 응답을 올바르게 처리할 수 있어야 한다. (37 ms)
- supertest로 진행
- 서버를 직접 생성하여 테스트하도록 진행
- https의 경우 응답을 리다이렉션하여 가져오도록 테스트 설계  - http-log-entity 테스트 케이스 작성
- HttpLogEntity 테스트
✓ 모든 속성을 가지고 인스턴스를 생성해야 한다.. (2 ms)
✓ path 속성이 undefined인 경우에 올바르게 처리해야 한다.
- log.repository 테스트 케이스 작성
- LogRepository는
✓ httpLog 정보를 성공적으로 삽입할 수 있어야 한다. (2 ms)
- log.service 테스트 케이스 작성
- LogService 테스트
- saveHttpLog()는
✓ httpLog를 성공적으로 저장해야 한다. (2 ms)
✓ DatabaseQueryError를 던져야 한다. (3 ms)
✓ 일반 오류를 DatabaseQueryError로 감싸서 던져야 한다.
server/utils 테스트 케이스 작성
- Utils 테스트
- validateHost()는
✓ host가 유효한 경우, 리턴해야 한다. (2 ms)
✓ host가 undefined인 경우, MissingHostHeaderError를 던져야 한다. (3 ms)
✓ host가 비어있는 경우, MissingHostHeaderError를 던져야 한다.
- validateIp()는
✓ IP가 유효한 경우, 에러를 던지지 않아야 한다.
✓ …

[BE] 프록시 서버 테스트 케이스 작성

---

front/src/constant/NavbarMenu.ts

#47
import할 때 파일이름이 잘못돼서 수정했습니다..

[FE] 빌드관련 에러 수정

---

backend/console-server/src/config/typeorm.config.ts
backend/console-server/src/project/dto/count-project-by-generation-response.dto.ts
backend/console-server/src/project/dto/count-project-by-generation.dto.ts
backend/console-server/src/project/project.controller.ts
backend/console-server/src/project/project.service.ts

[BE] 기수별 전체 프로젝트 갯수 응답 API 구현

---

backend/console-server/src/project/dto/create-project.dto.ts

fix: CreateProjectDto 중복 해결

---

backend/console-server/src/clickhouse/util/metric-expressions.ts
backend/console-server/src/log/log.controller.ts
backend/console-server/src/log/log.repository.ts
backend/console-server/src/log/log.service.ts

[BE] 기수 내 응답 성공률 api 구현

---

.gitignore
backend/console-server/src/project/project.controller.ts
backend/console-server/src/project/project.service.ts

[BE] 기수별 프로젝트 API 응답 변경

---

.gitignore

setting: gitignore 수정

---

backend/console-server/src/project/dto/find-by-generation-response.dto.ts
backend/console-server/src/project/project.service.ts

[BE] 기수별 프로젝트 목록 API 응답 타입 수정

---

.gitignore
backend/proxy-server/docker-compose.yml

[BE} fix: git 실수 rollback

---

backend/console-server/src/main.ts
backend/console-server/src/project/dto/create-project.dto.ts
backend/console-server/src/project/dto/find-by-generation-response.dto.ts

feat: 기수별 프로젝트 목록 API 응답 수정

---

backend/console-server/src/log/log.controller.ts
backend/console-server/src/project/project.service.ts

#127 
- project.service.ts 에서 테스트용으로 이메일 기능 주석했던 것 제거
- log.controller.ts import 구문 컴파일 에러 수정

[BE] 주석 제거 및 log.controller.ts import 컴파일 에러 수정

---

backend/name-server/src/server/server.ts
backend/proxy-server/package.json
backend/proxy-server/src/app.ts
backend/proxy-server/src/common/error/create-system.error.ts
backend/proxy-server/src/domain/log/log.handler.ts
backend/proxy-server/src/domain/proxy/proxy.handler.ts
backend/proxy-server/src/domain/proxy/proxy.service.ts
backend/proxy-server/src/index.ts
backend/proxy-server/src/server/server.ts
backend/proxy-server/test/integration.test.ts

#121 
- index.ts → app.ts → server.ts 구조로 변경
- server.ts에서 ProxyHandler와 ErrorHandler로 분리
- ProxyHandler & ProxyService로 비지니스 로직도 분리
- 파일 구조가 좀 난잡한 것 같은데 어떻게 더 리팩토링하면 좋을지
- 간단하게 server.ts 코드를 분리하는 정도로 해뒀는데, 어떤 리팩토링을 하면 좋을지

[BE] Proxy Server 리팩토링

---

backend/console-server/src/app.controller.spec.ts
backend/console-server/src/log/dto/get-avg-elapsed-time.dto.ts
backend/console-server/src/log/dto/get-traffic-daily-difference-response.dto.ts
backend/console-server/src/log/dto/get-traffic-rank.dto.ts
backend/console-server/src/log/dto/get-traffic-top5-chart-response.dto.ts
backend/console-server/src/log/dto/get-traffic-top5-chart.dto.ts
backend/console-server/src/log/log.contorller.spec.ts
backend/console-server/src/log/log.controller.ts
backend/console-server/src/log/log.repository.ts
backend/console-server/src/log/log.service.ts
backend/console-server/src/log/metric/traffic-rank-top5.metric.ts
backend/console-server/src/log/metric/trafficChart.metric.ts
backend/console-server/test/app.e2e-spec.ts

#132 
트래픽 TOP 5 프로젝트에 대한 작일의 트래픽 차트 데이터를 API 구현
- 다음 쿼리로 TOP 5 프로젝트의 호스트로 쿼리한 후 해당 호스트에 대한 작일의 트래픽 데이터를 응답한다.
- 트래픽 데이터 간격은 1분
- TOP 5 호스트 별 그룹핑
```sql
WITH top_hosts AS (
SELECT host
FROM http_log
WHERE timestamp >= {startTime: DateTime64(3)}
AND timestamp < {endTime: DateTime64(3)}
GROUP BY host
ORDER BY count() DESC
LIMIT 5
)
SELECT
host,
groupArray(
(
toDateTime64(toStartOfInterval(timestamp, INTERVAL 1 MINUTE), 0),
requests_count
)
) as traffic
FROM (
SELECT
host,
toDateTime64(toStartOfInterval(timestamp, INTERVAL 1 MINUTE), 0) as timestamp,
count() as requests_count
FROM http_log
WHERE timestamp >= {startTime: DateTime64(3)}
AND timestamp < {endTime: DateTime64(3)}
AND host IN (SELECT host FROM top_hosts)
GROUP BY
host,
timestamp
ORDER BY
timestamp
)
GROUP BY host;
```
응답 예시
```json …
```

[BE] 트래픽 TOP5 프로젝트에 대한 라인 차트 데이터 쿼리 API

---

backend/name-server/src/server/server.ts
backend/proxy-server/ecosystem.config.cjs

fix: 중복 타입 & 엔트리포인트 수정

---

backend/proxy-server/src/domain/proxy/proxy.service.ts

fix: https:// 오타 수정

---

backend/proxy-server/src/domain/proxy/proxy.service.ts

fix: 항상 https 적용

---

backend/proxy-server/src/domain/proxy/proxy.service.ts

merge to main

---

front/src/api/get.ts
front/src/chart/LineChart.tsx
front/src/component/organism/MainTrafficChart.tsx
front/src/component/page/MainPage.tsx
front/src/hook/api/useTop5Traffic.ts
front/src/hook/useDefaultOption.ts
front/src/type/api.ts

#47
트래픽차트에 api로 실제 데이터를 넣고 적용했습니다!

[FE] 메인페이지 트래픽 차트 데이터적용

---

backend/console-server/src/clickhouse/util/date-range.ts
backend/console-server/src/log/log.contorller.spec.ts
backend/console-server/src/log/log.repository.spec.ts
backend/console-server/src/log/log.service.spec.ts
backend/console-server/src/log/log.service.ts
backend/console-server/src/project/project.service.spec.ts

- 테스트 코드 수정
- 대부분 Dto 변경 혹은 메서드명 변경에 따른 미통과 케이스

[BE] 코드 수정에 따른 미통과 테스트케이스 수정

---

backend/console-server/src/log/log.module.ts

[BE] log controller 삭제

---

backend/console-server/src/clickhouse/query-builder/time-series.query-builder.ts
backend/console-server/src/log/analytics/analytics.controller.spec.ts
backend/console-server/src/log/analytics/analytics.controller.ts
backend/console-server/src/log/analytics/analytics.repository.spec.ts
backend/console-server/src/log/analytics/analytics.repository.ts
backend/console-server/src/log/analytics/analytics.service.spec.ts
backend/console-server/src/log/analytics/analytics.service.ts
backend/console-server/src/log/analytics/dto/get-project-dau-response.dto.ts
backend/console-server/src/log/analytics/dto/get-project-dau.dto.ts
backend/console-server/src/log/analytics/metric/dau.metric.ts
backend/console-server/src/log/rank/rank.controller.spec.ts
backend/name-server/src/database/query/dau-recorder.ts

#112 
---
- 빈 날짜 채우기, 날짜 포맷팅 용도 헬퍼 함수를 해당 클래스에 private 메소드로 작성하였는데, 적절할까요?
- 많지는 않지만 특히 날짜 조작 관련해서 비슷한 로직이 자꾸 등장하니 공통 util 폴더를 하나 둘까 싶네요.. 아니면 각 도메인에 util 파일 만들기? 어떻게 생각하시나요?
- 쿼리빌더 timeBetween에 컬럼명 인자 추가하였습니다. defualt는 timestamp로 하여 기존 코드 수정 없게 했습니다. 쿼리빌더 timeBetween에 기존 where문 있다면 AND 넣게 수정하였습니다.
- 린터 다들 잘 확인해주세요..! 안되는 것 같으면 직접 마지막에 CLI로 돌려주세용.. 제가 돌려도 전혀 상관은 없지만 충돌날까봐 걱정됩니다 ㅠㅠ
- 테스트 통과 확인
PASS  src/log/analytics/analytics.controller.spec.ts
PASS  src/log/analytics/analytics.service.spec.ts
PASS  src/log/analytics/analytics.repository.spec.ts
- 스웨거에서 로컬 디비로 테스트

[BE] 개별 프로젝트 DAU 수정 요구사항 반영 

---

frontend/src/component/organism/ProjectDAU.tsx
frontend/src/index.tsx

#161
tsc관련 에러가 있어서 수정해 다시 올립니다!

[FE] 배포관련 에러 수정

---

backend/proxy-server/docker-compose.yml
backend/proxy-server/package-lock.json
backend/proxy-server/package.json
backend/proxy-server/src/app.ts
backend/proxy-server/src/database/mysql/mysql-database.ts
backend/proxy-server/src/database/query/project-cache.repository.redis.ts
backend/proxy-server/src/database/redis/redis-database.ts
backend/proxy-server/src/domain/project/project-cache.repository.ts
backend/proxy-server/src/domain/project/project.service.ts
backend/proxy-server/src/domain/proxy/proxy.service.ts
backend/proxy-server/src/index.ts
backend/proxy-server/src/server/config/fastify.config.ts
backend/proxy-server/src/server/server.ts
backend/proxy-server/src/server/utils.ts

[BE] 프록시 서버 요청 Host에 대한 ip 캐싱 구현

---

frontend/package-lock.json
frontend/package.json
frontend/src/api/get.ts
frontend/src/chart/LineChart.tsx
frontend/src/chart/PieChart.tsx
frontend/src/chart/PolarAreaChart.tsx
frontend/src/component/organism/MainTrafficChart.tsx
frontend/src/component/organism/ProjectDAU.tsx
frontend/src/component/organism/ProjectElapsedTime.tsx
frontend/src/component/organism/ProjectSuccessRate.tsx
frontend/src/component/organism/ProjectTrafficChart.tsx
frontend/src/component/page/ProjectDetailPage.tsx
frontend/src/constant/Date.ts
frontend/src/hook/api/useProjectTraffic.ts
frontend/src/index.tsx
frontend/src/type/Date.ts
frontend/src/type/api.ts

#161
개별프로젝트 페이지의 DAU, 트래픽차트를 완성했습니다.
기존에 사용하고있는 apexChart라이브러리의 HeatMap차트를 이용해 DAU를 그리려고 했습니다.
문제가, 6x5를 반드시 다 그리고 채워넣어야 한단 점이였습니다.
기존에 스트릭을 생각했기에, 넘치는 날짜가 있는건 이상하다고 판단해 다른 차트라이브러리인 nivo를 이용했습니다.
nivo의 TimeRange차트를 이용해 날짜를 from에서 to로 설정했더니, 원하는대로 스트릭형태로 잘 그릴 수 있었습니다.
1. 개별페이지 트래픽차트 색상 추천받습니다.
2. select디자인 추천 받습니다.

[FE] 개별프로젝트 페이지 완성

---

frontend/src/component/molecule/NavbarRanking.tsx
frontend/src/component/organism/MainTrafficChart.tsx
frontend/src/index.css

#161
- Navbar랭킹관련 글씨 크기를 축소했습니다.
- 배포시에 Traffic차트에서 xaxis,yaxis div때문에 부들거리던 버그를 수정했습니다.

[FE] 개별프로젝트 페이지 짜잘한 수정

---

backend/proxy-server/Dockerfile
backend/proxy-server/docker-compose.yml
backend/proxy-server/package.json

- 프록시 서버 docker-compose.yml, DOCKERFILE 타임존 설정 추가
- pakcage.json lint 스크립트 추가
- docker-compose.yml에 TZ 설정 추가 및 network 설정 수정
- DockerFile에 tzdata 패키지 설치 스크립트 추가
- package.json lint 스크립트 추가

[BE] yml 파일 설정, docker 타임존 설정

---

backend/console-server/src/log/rank/dto/get-dau-rank-response.dto.ts
backend/console-server/src/log/rank/dto/get-elapsed-time-rank-response.dto.ts
backend/console-server/src/log/rank/dto/get-success-rate-rank-response.dto.ts
backend/console-server/src/log/rank/dto/get-traffic-rank-response.dto.ts
backend/console-server/src/log/rank/rank.controller.spec.ts
backend/console-server/src/log/rank/rank.controller.ts
backend/console-server/src/log/rank/rank.service.spec.ts
backend/console-server/src/log/rank/rank.service.ts

[BE] 랭킹 페이지 응답 형식 수정

---

backend/console-server/nginx.conf
backend/console-server/src/log/rank/rank.controller.ts

- 랭킹페이지 트래픽 랭킹 ResponseBody 타입 수정
- green 컨테이너 weight backup -> 1로 수정

[BE] 스웨거 및 nginx 설정 수정

---

backend/console-server/src/log/rank/dto/get-elapsed-time-rank-response.dto.ts
backend/name-server/src/database/query/dau-recorder.ts

[BE] DAU 날짜 형식 수정

---

backend/console-server/src/log/rank/dto/get-success-rate-rank-response.dto.ts
backend/console-server/src/log/rank/rank.repository.spec.ts
backend/console-server/src/log/rank/rank.repository.ts
backend/console-server/src/log/rank/rank.service.ts
backend/console-server/src/log/traffic/dto/get-traffic-top5-response.dto.ts
backend/console-server/src/log/traffic/metric/traffic-rank-top5.metric.ts
backend/console-server/src/log/traffic/traffic.repository.ts
backend/console-server/src/log/traffic/traffic.service.spec.ts
backend/console-server/src/log/traffic/traffic.service.ts

#
- 응답시간 랭킹
- 성공률 랭킹
- 사이드바 top5 프로젝트

[BE] 성공률랭킹 소수점 제거 / 조회 기간 수정 / 사이드바 데이터 형식 수정

---

backend/proxy-server/src/domain/log/log.handler.ts
backend/proxy-server/src/domain/log/log.service.ts
backend/proxy-server/src/domain/proxy/proxy.handler.ts
backend/proxy-server/src/server/config/server.initializer.ts

[BE] 프록시 서버 성능 개선

---

backend/console-server/Dockerfile
backend/proxy-server/Dockerfile

[BE] pm2 제거

---

backend/proxy-server/Dockerfile

[BE] fix: 빌드 중복

---

backend/console-server/Dockerfile
backend/proxy-server/Dockerfile

[BE] Merge to main

---

backend/proxy-server/Dockerfile

fix: 진입점 수정

---

backend/proxy-server/src/database/clickhouse/config/clickhouse.config.ts

[BE] feat: wait for async insert 0

---

backend/proxy-server/Dockerfile
backend/proxy-server/src/database/clickhouse/config/clickhouse.config.ts

[BE] Merge to main 

---

backend/console-server/src/log/traffic/dto/get-traffic-by-project-response.dto.ts
backend/console-server/src/log/traffic/metric/traffic-count-by-project.metric.ts
backend/console-server/src/log/traffic/traffic.repository.ts
backend/console-server/src/log/traffic/traffic.service.spec.ts
backend/console-server/src/log/traffic/traffic.service.ts

- #108 
- 인증서 갱신 쉘 스크립트 작성하였는데, 프로젝트에 포함되는 파일은 아니라 PR에는 담지 않았습니다.
- `/home/watchducks/scripts` 경로에 스크립트 파일과 로그 있습니다.

[BE] 개별 프로젝트 트래픽 요구사항 반영 (cf. 인증서 갱신 쉘 스크립트 crontab 적용)

---

frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/boundary/MainBoundary.tsx
frontend/src/component/molecule/NavbarCustomSelect.tsx
frontend/src/component/molecule/NavbarDefaultSelect.tsx
frontend/src/component/molecule/NavbarMenu.tsx
frontend/src/component/molecule/NavbarRanking.tsx
frontend/src/component/molecule/NavbarSelect.tsx
frontend/src/component/molecule/RankingItem.tsx
frontend/src/component/molecule/RankingTab.tsx
frontend/src/component/organism/NavBar.tsx
frontend/src/component/organism/NavbarSelectWrapper.tsx
frontend/src/component/organism/ProjectTrafficChart.tsx
frontend/src/component/page/MainPage.tsx
frontend/src/component/page/ProjectPage.tsx
frontend/src/component/page/RankingPage.tsx
frontend/src/component/template/NabvarLayout.tsx
frontend/src/store/NavbarStore.ts
frontend/tsconfig.app.json
frontend/tsconfig.json
frontend/vite.config.ts

#226 
버그를 수정했습니다.
Traffic 랭킹을 누르면 Select가 안바뀌던현상을 수정했습니다.
기존에 Navbar에서 Props를 select까지 4번정도 걸쳐서 뿌렸는데, zustand를 써서 전역상태로 관리하였습니다.
또한 다른 페이지들에서도 이를 적용해서 generation을 전역상태로 수정했습니다.

[FE] 버그 및 코드 리팩토링

---

frontend/src/component/molecule/NavbarSelect.tsx

Navbar의 Select에서 그룹을 선택해도 리다이렉트가 안되던 버그를 수정했습니다.

[FE] select로 프로젝트선택시 리다이렉트가 안되던 부분수정

---

frontend/index.html
frontend/src/component/organism/ProjectDAU.tsx
frontend/src/component/organism/ProjectTrafficChart.tsx
frontend/src/component/organism/RegisterForm.tsx
frontend/src/component/page/RegisterPage.tsx

#262
1. 개별 프로젝트 페이지에서 dau마지막 날짜옆을 호버시에, 떨리던 현상을 수정했습니다.
호버시 툴팁관련 공간부족이라 생각해 마진을 더 주었습니다.
2. 성능 관련해서 cdn을 preload했습니다.

[FE] 개별프로젝트 페이지 dau호버시 떨림 현상수정

---

backend/console-server/src/config/typeorm.config.ts
backend/console-server/src/log/analytics/analytics.controller.ts
backend/console-server/src/log/success-rate/success-rate.controller.ts
backend/console-server/src/log/traffic/dto/get-traffic-by-project-response.dto.ts
backend/console-server/src/log/traffic/traffic.controller.ts
backend/console-server/src/log/traffic/traffic.service.spec.ts
backend/console-server/src/log/traffic/traffic.service.ts
backend/console-server/src/project/project.controller.ts

- #122 
- #108 
- total 수정
- 캐시 적용 추가
- 갱신 주기 감소
- 테스트, 린터 확인

[BE] total 수정, 캐시 적용 추가, 갱신 주기 감소

---

frontend/src/component/organism/ProjectDAU.tsx

#262
패딩대신 마진을 줬고, overflow hidden옵션을 추가했습니다.

fix: 페이지 떨림현상 수정

---

frontend/src/component/organism/ProjectTrafficChart.tsx
frontend/src/type/api.ts

#280
개별프로젝트페이지에 해당서비스를 리다이렉트 해주는 기능을 추가했습니다.

[FE] 개별페이지에서 해당 서비스 리다이렉트 해주는 기능 추가

---

backend/proxy-server/src/server/handler/proxy.handler.ts

fix: 멀티파트 제거

---

frontend/src/boundary/CustomErrorFallback.tsx
frontend/src/chart/README.md
frontend/src/component/molecule/NavbarRanking.tsx
frontend/src/component/organism/ProjectTrafficChart.tsx
frontend/src/router/README.md
frontend/src/store/README.md

1. 디렉토리에 작성못한 리드미를 추가했습니다.
2. NavbarRanking에 글씨 크기를 수정했습니다.
3. 개별프로젝트페이지의 리다이렉트 링크를 수정했습니다.

[FE] Merge to main

---

backend/proxy-server/src/server/handler/proxy.handler.ts

[BE] 호스트 상실 수정

---

frontend/src/component/template/NabvarLayout.tsx

[FE] Navbar 토글시 영역이 남아있던 현상 수정

---

frontend/src/component/organism/MainData.tsx

랜딩페이지에 토탈 트래픽 수 단위를 K로 수정했습니다.

[FE] MainData 트래픽 수 K로 수정

---

frontend/src/api/get/index.ts
frontend/src/hook/api/useGroupNames.ts
frontend/src/hook/api/useIsExistGroup.ts
frontend/src/hook/api/useProjectDAU.ts
frontend/src/hook/api/useProjectElapsedTime.ts
frontend/src/hook/api/useProjectSuccessRate.ts
frontend/src/hook/api/useProjectTraffic.ts
frontend/src/hook/api/useRankData.ts
frontend/src/hook/api/useRankings.ts
frontend/src/hook/api/useTop5ResponseTime.ts
frontend/src/hook/api/useTop5Traffic.ts
frontend/src/hook/api/useTotalDatas.ts
frontend/src/hook/useDarkMode.ts

잘들 지내시나요?
간단한 리팩토링해서 pr올리고 혼자 머지합니다 ㅎㅎ.
- 배럴파일 사용한 get API를 수정했습니다.
- 랭킹페이지의 캐싱시간을 수정했습니다.
[배럴파일지양하기](https://velog.io/@eunnbi/About-Vite)

[FE] 간단한 리팩토링

---

frontend/src/hook/api/useRankData.ts
frontend/src/hook/api/useTotalDatas.ts

- 메인페이지에서 totalData요청 시, 병렬요청으로 최적화
- 랭킹페이지 캐싱을 다음날까지 하도록 시간 수정

[FE] 데이터 요청 수정
